configName: pic32cm_mc00_curiosity_pro
folderName: ''
format_version: v1.0
frameworkPath: ../../../..
processor: PIC32CM1216MC00048
projectName: ''
settings:
  PackageFilter: core;csp;
  FORCE_OPTIMIZATION: 'false'
  GENERATE_BACKUP: 'true'
  TRUSTZONE: 'false'
  CMSISPath: .\dev_packs\arm\CMSIS\5.8.0
  MERGE_STRATEGY: USER_ALL
  DFPPath: .\dev_packs\Microchip\PIC32CM-MC_DFP\1.0.15\atdf\PIC32CM1216MC00048.atdf
