format_version: v1.0
type: UniqueComponent
attributes: {id: eic}
children:
- type: Symbols
  children:
  - type: Hex
    attributes: {id: EIC_ASYNCH}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: eic, value: '0'}
  - type: Boolean
    attributes: {id: EIC_CHAN_6}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: 'true'}
  - type: Boolean
    attributes: {id: EIC_CONFIG_FILTEN_10}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
  - type: Boolean
    attributes: {id: EIC_CONFIG_FILTEN_6}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
  - type: KeyValueSet
    attributes: {id: EIC_CONFIG_SENSE_10}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '4'}
  - type: KeyValueSet
    attributes: {id: EIC_CONFIG_SENSE_6}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '4'}
  - type: Hex
    attributes: {id: EIC_EXTINTEO}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: eic, value: '64'}
  - type: Boolean
    attributes: {id: EIC_EXTINTEO_10}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: 'true'}
  - type: Boolean
    attributes: {id: EIC_EXTINTEO_6}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: 'true'}
  - type: Hex
    attributes: {id: EIC_INT}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: eic, value: '0'}
  - type: Menu
    attributes: {id: EIC_MENU6}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
- type: ElementPosition
  attributes: {x: '430', y: '60', id: eic}
